Add port endpoints for services
NetsBlox/NetsBlox pull request #3030
Opened 2021-03-02 22:35 UTC by gsteinLTU

Closes #3022

Adds `api/services/iotscape/port`, `api/roboscape/port`, and `api/services/phone-iot/port` endpoints. They either provide the port or respond that it is not enabled (Should the endpoints return a different status code for that case?).

2021-03-02 22:41 UTC, brollb requested changes
This looks great. Nice work. My only question is about the edits to speck.js - were those an accident? They seem unrelated to the rest of the PR.

2021-03-02 22:41 UTC, brollb commented on src/server/services/procedures/roboscape/ciphers.js
> +const Speck32 = require('./speckjs/src/ciphers/speckNative.js');
Why has this been changed? I suspect this was an accident since it doesn't seem related to any of the other changes.

2021-03-03 04:34 UTC, gsteinLTU commented
Sorry, that's a change I have to make every time I make a branch on Windows/WSL and I accidentally threw it in with the rest. Do you want me to separate it out?

2021-03-03 19:48 UTC, brollb commented
If you don't mind separating it out, that would be great!

2021-03-03 20:54 UTC, brollb approved these changes

2021-03-03 20:55 UTC, gsteinLTU commented
It's now separated out.

2021-03-03 20:57 UTC, merged

2021-03-03 20:59 UTC, brollb commented
Looks good! Thanks, @gsteinLTU!