added Array type bounds and complex inner types
NetsBlox/NetsBlox pull request #3084
Opened 2021-04-16 00:11 UTC by dragazo

This PR adds two features to the `Array` input type. First, it adds upper and lower bounds for length, like `BoundedString` does. This can be specified like `@param {Array<Any, 2, 5>}`. Second, it adds support for complex inner types. It looks like the parser for inner types always yields an object of form `{ name: String, params: Any[] }` for inner types having angled brackets, so I added a wrapper for working with those. So now you can do complex types like a list of 0/1 as `@param {Array<Enum<0,1>>}`. Or perhaps more useful, `@param {Array<BoundedNumber<0>>}` for a list of non-negative numbers.

2021-04-16 21:02 UTC, brollb requested changes
Nice work! I left a couple minor comments.

2021-04-16 21:02 UTC, brollb commented on src/server/services/input-types.js
> +    const innerType = grabType(_innerType);
Maybe renaming this to
```javascript
const [typeParam, min, max] = params;
const innerType = getTypeParser(typeParam);
```
Thoughts?

2021-04-16 21:02 UTC, brollb commented on src/server/services/input-types.js
> +    const innerType = grabType(_innerType);
If you add some default values for `min`, `max`, you can probably simplify some of the code further:
```javascript
types.Array = (input, params=[]) => {
    const [typeParam, min=0, max=Infinity] = params;
    const innerType = getTypeParser(typeParam);
```

2021-04-20 05:29 UTC, dragazo commented
Ah, sorry, looks like you beat me to the edits. The `not a list` error message was an attempt at making errors for nested arrays clearer, but it wasn't consistent with error messages for other types like `Number` that just say `Error` if they fail to parse.

I didn't know that default value syntax for array unpacking; that's really convenient. I just checked in Node, and it looks like if we do that, we don't need the `if (min)` and `if (max)` parts anymore. I just removed them in the most recent commit.

2021-04-20 11:42 UTC, brollb approved these changes

2021-04-20 11:43 UTC, merged