Covid-19 Vaccine RPCs
NetsBlox/NetsBlox pull request #3104
Opened 2021-04-28 01:59 UTC by MaririW

I have added an RPC to get Vaccination data. The data source is from [OWID](https://github.com/owid/covid-19-data/tree/master/public/data). It is linked to the source and auto update itself every 24 hours.

2021-04-28 21:03 UTC, dragazo requested changes
Nice, good work! (This is Devin btw). I left some comments on various pieces. Mostly they're jsdoc or formatting related; we want to be especially careful about what we expose to the user and make sure we maintain consistency. Brian will probably also comment on anything I missed or different ways to address them.

I found one cache-related bug, and I think the user input dates aren't being sanitized, which could lead to problems with your ordering scheme (see comments for details). I'll test the service more thoroughly after those are updated.

2021-04-28 23:01 UTC, dragazo commented on src/server/services/procedures/covid-19/covid-19.js
> +COVID19.getCountry = async function() {
Also maybe `getVaccinationCountries` or similar would be better to avoid confusion with other rpcs in this service

2021-04-30 04:53 UTC, dragazo commented on src/server/services/procedures/covid-19/covid-19.js
> +    if (startDate === '' && endDate ==='') return raw;
Actually, apparently we do have a `Date` parser, but it just uses the `Date` object constructor, which is super permissive in terms of giving errors, and doesn't let you specify the input format, so you'd just have to use whatever it uses if you go that route.

2021-07-26 00:23 UTC, dragazo commented
@brollb I went ahead and addressed the comments I left from before and fixed the merge conflicts, so this is ready to be looked at again.

2021-08-09 19:48 UTC, brollb commented
This has been updated and merged in #3247. Thanks, @MaririW, @dragazo!

2021-08-09 19:48 UTC, closed without merging